# Generated by Django 2.2 on 2019-05-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='FILES1',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='static/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='TEMP_FILES',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='static/uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='FILES',
        ),
    ]
